/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <bsp.h>

int main(void)
{
	//activate clock for GPIOE to work
	RCC_AHB1ENR->bits.GPIOAEN = 1;

	GPIO_MODE_SET(GPIOA, 7, GPIO_MODE_OUTPUT);
	// ... completar resto de la configuración

    /* Loop forever */
	for(;;) {
		// ... encender led
		delay(1000000);
		// ... apagar led
		delay(1000000);
	}
}
