/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <bsp.h>

int main(void)
{
	//activate clock for GPIOE to work
	//RCC_AHB1ENRRAW |= 0x10;
	RCC_AHB1ENR->bits.GPIOAEN = 1;

	GPIO_MODE_SET(GPIOA, 7, GPIO_MODE_OUTPUT);
	GPIO_OTYPE_SET(GPIOA, 7, GPIO_OTYPE_PP);
	GPIO_OSPEED_SET(GPIOA, 7, GPIO_OSPEED_HIGH);
	GPIO_PUPD_SET(GPIOA, 7, GPIO_PUPD_NONE);

    /* Loop forever */
	for(;;) {
		GPIO_PIN_WRITE(GPIOA, 7, GPIO_STATE_ONE);
		delay(1000000);
		GPIO_PIN_WRITE(GPIOA, 7, GPIO_STATE_ZERO);
		delay(1000000);
	}
}
