/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define GPIOA_BASE_ADDR 0x40020000
#define RCC_AHB1ENR 0x40023830

void delay(int loops) {
	for (int i = 0; i < loops; i++) {
		__asm("nop");
	}
}

int main(void)
{
    //activar reloj de GPIOA en RCC_AHB1ENR
    //configurar Pin0-GPIOA como salida
    //configurar Pin0-GPIOA modo push-pull
    //configurar Pin0-GPIOA velocidad alta
    //configurar Pin0-GPIOA con pullup/down desactivado

    /* Loop forever */
    for(;;) {
        //encender LED
        delay(1000000);
        //apagar LED
        delay(1000000);
    }
}
